version: '3.8'

services:
  petclinic-db-server:
    container_name: petclinic-db-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ClinicaMascotas2026#
    volumes:
      - mssql_data:/var/opt/mssql

  petclinic-api:
    container_name: petclinic-api
    build:
      context: .
      dockerfile: src/PetClinic.Api/Dockerfile
    ports:
      - "5210:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=petclinic-db-server;Database=PetClinicDb;User Id=sa;Password=ClinicaMascotas2026#;TrustServerCertificate=True;
    depends_on:
      - petclinic-db-server

  petclinic-web:
    container_name: petclinic-web
    build:
      context: ./src/PetClinic.Web
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - petclinic-api

  petclinic-portalweb:
    container_name: petclinic-portalweb
    build:
      context: ./src/PetClinic.PortalWeb
      dockerfile: Dockerfile
    ports:
      - "5211:80"
    depends_on:
      - petclinic-api

volumes:
  mssql_data:
